server:
  port:
    8082

spring.devtools.livereload.enabled:
  false

spring.thymeleaf.cache:
  false

spring.datasource:
  name:
    cloud_db
  driverClassName:
    org.h2.Driver
  url:
    jdbc:h2:mem:cloud_db;DB_CLOSE_ON_EXIT=FALSE
  username:
    root
  password:
    root

spring.h2.console.enabled: true
spring.h2.console.path: /h2-console

spring:
  jpa:
    show-sql:
      true
    hibernate:
      ddl-auto:
        update
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.H2Dialect
    open-in-view:
      true

logging:
  file:
    path: /var/logs/
    file: TacoCloud.log
  level:
    root: WARN
    org:
      springframework:
      security: DEBUG
